// Code generated by protoc-gen-cuckoo 0.1, DO NOT EDIT.
// source: kv.proto

package model

import (
	"fmt"

	etcdv3 "github.com/carolove/cuckoo/net/grpc/lb/etcdv3/wothing"
	"github.com/cuigh/auxo/util/lazy"
)

var (
	kv = &kvClient{lazyValue: lazy.Value{New: createKV}}
)

func GetKV() KVClient {
	v, err := kv.lazyValue.Get()
	if err != nil {
		fmt.Println("KV service Get failed!")
		return nil
	}

	return v.(KVClient)
}

func createKV() (interface{}, error) {
	conn, err := etcdv3.NewRPCConn("localhost:2379", "protoc-gen-cuckoo/kv", "127.0.0.1:8081")
	if err != nil {
		panic(err)
	}

	client := NewKVClient(conn)
	return interface{}(client), nil
}

type kvClient struct {
	lazyValue lazy.Value
}
