// Code generated by protoc-gen-cuckoo 0.1, DO NOT EDIT.
// source: kv.proto

package model

import (
	"fmt"

	etcdv3 "github.com/carolove/cuckoo/net/grpc/lb/etcdv3/wothing"
	"github.com/cuigh/auxo/util/lazy"
)

var (
	kv = &kvClient{lazyValue: lazy.Value{New: createKV}}
)

func GetKV() KVClient {
	in, err := kv.lazyValue.Get()
	if err != nil {
		fmt.Println("KV service Get failed!")
		return nil
	}
	conn, err := etcdv3.NewConn("localhost:2379", "composetesst/kv", "127.0.0.1:8081")
	if err != nil {
		panic(err)
	}
	return kv
}

type kvClient struct {
	lazyValue lazy.Value
}
